#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path


BEGIN = "<!-- BEGIN AUTO-GENERATED INDEX -->"
END = "<!-- END AUTO-GENERATED INDEX -->"


def _rel_link(from_path: Path, to_path: Path) -> str:
    rel = os.path.relpath(to_path.as_posix(), start=from_path.parent.as_posix())
    return rel.replace("\\", "/")


def _load_nav(nav_path: Path) -> dict:
    data = json.loads(nav_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit(f"nav must be a JSON object: {nav_path}")
    return data


def _render_index(skill_path: Path, nav_path: Path) -> str:
    nav = _load_nav(nav_path)
    doc_root = nav_path.parent
    lines: list[str] = []

    top = nav.get("top", [])
    if isinstance(top, list):
        lines.append("## 快速开始")
        for item in top:
            if not isinstance(item, dict):
                continue
            title = item.get("title")
            path = item.get("path")
            if isinstance(title, str) and isinstance(path, str):
                lines.append(f"- [{title}]({_rel_link(skill_path, (doc_root / path).resolve())})")
        lines.append("")

    sections = nav.get("sections", [])
    if isinstance(sections, list):
        for section in sections:
            if not isinstance(section, dict):
                continue
            title = section.get("title")
            items = section.get("items", [])
            if not isinstance(title, str) or not isinstance(items, list):
                continue
            lines.append(f"## {title}")
            for item in items:
                if not isinstance(item, dict):
                    continue
                it_title = item.get("title")
                it_path = item.get("path")
                if isinstance(it_title, str) and isinstance(it_path, str):
                    lines.append(f"- [{it_title}]({_rel_link(skill_path, (doc_root / it_path).resolve())})")
            lines.append("")

    if not lines:
        return "- (no pages found yet)\n"

    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def update_skill_index(skill_path: Path, nav_path: Path) -> None:
    text = skill_path.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise SystemExit(f"Missing index markers in {skill_path}")

    before, rest = text.split(BEGIN, 1)
    _old, after = rest.split(END, 1)

    new_index = _render_index(skill_path, nav_path)
    updated = before + BEGIN + "\n" + new_index + END + after

    updated = re.sub(rf"{re.escape(END)}\n+", END + "\n", updated)
    skill_path.write_text(updated, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Update SKILL.md auto-generated doc index from local mirror.")
    parser.add_argument("--skill", required=True, help="Path to skills/opencode-docs/SKILL.md")
    parser.add_argument("--nav", required=True, help="Path to nav.json generated by organize_docs.py")
    args = parser.parse_args()

    skill_path = Path(os.path.expanduser(args.skill)).resolve()
    nav_path = Path(os.path.expanduser(args.nav)).resolve()

    if not skill_path.exists():
        raise SystemExit(f"Skill not found: {skill_path}")
    if not nav_path.exists():
        raise SystemExit(f"Nav not found: {nav_path}")

    update_skill_index(skill_path, nav_path)
    print(f"Updated index in: {skill_path}")


if __name__ == "__main__":
    main()
